n_jobs: 30
data:
  n_dataset_train: 5
  n_dataset: 10
  # graph
  d: 10
  e_coef: 1
  dag_type: [ER, SF]
  seed: 123
  # data
  N: 1000
  method: linear
  sem_type: gauss
  noise_scale: 1.

model:
  run: True
  verbose: false
  n_posterior_samples: 100
  # dataloader
  seed_dataset: 0
  split: [0.9, 0.1]
  num_worker: 0
  batch_size: 64 # Batch size. i 
  # args_achitecture: args for network architecture of FuntionalModel
  seed_model: 0
  hidden_dims: [] 
  factorize_type: NULL
  temp_w: 1.0
  temp_p: 0.3
  hard: true
  lr_dag: 0.01 
  lr_f: 5.e-3 
  l2_f: 1.e-4
  lambda_p_score: 1.e-4 # regularize for kl_p_score
  prior_p_scale: 0.1
  lambda_e: 3.e-3 # regularize for kl_edge
  prior_edge_prob: 0.01
  scaled: False
  # Training
  max_epochs: 500
  val_freq: 10
  log_freq: 100
  device: cuda
