n_jobs: 10
data:
  n_dataset: 10
  # graph
  d: [10] # just for demo. In the paper: [10, 50]
  e_coef: 1
  dag_type: [ER, SF]
  seed: 123
  # data
  N: 1000
  method: linear 
  sem_type: gauss
  noise_scale: 1.
methods:
  VCUDA:
    run: True
    verbose: false
    n_posterior_samples: 100
    # dataloader
    seed_dataset: 0
    split: [0.9, 0.1]
    num_worker: 0
    batch_size: 64 # Batch size. i 
    # args_achitecture: args for network architecture of FuntionalModel
    seed_model: 0
    hidden_dims: [] 
    factorize_type: NULL
    temp_w: 1.0
    temp_p: 0.3
    hard: true
    lr_dag: 0.01 
    lr_f: 5.e-3 
    l2_f: 1.e-4
    lambda_p_score: 1.e-4 # regularize for kl_p_score
    prior_p_scale: 0.1
    lambda_e: 3.e-3 # regularize for kl_edge
    prior_edge_prob: 0.01
    scaled: False
    # Training
    max_epochs: 500
    val_freq: 10
    log_freq: 100
    device: cuda

  DDS:
    run: false
    verbose: false
    # evaluation
    n_posterior_samples: 100
    # dataloader
    seed_dataset: 0
    split: [.9, .1]
    num_worker: 0
    batch_size: 64 # Batch size. int
    # Architecture parameters
    seed_model: 123  # Seed to init model. int
    ma_hidden_dims: [] #[16, 16, 16]  # Output dimension. int
    ma_architecture: linear  # Output dimension. int
    ma_fast: false  # Output dimension. int
    pd_initial_adj: NULL  # Output dimension. int
    pd_temperature: 1.0  # Output dimension. int
    pd_hard: true  # Output dimension. int
    pd_order_type: topk  # Output dimension. int
    pd_noise_factor: 1.0  # Hidden dimensions. list of ints
    ma_lr: 1.e-3  # Learning rate. float
    pd_lr: 1.e-2  # Learning rate. float
    loss: ELBO  # Loss name. string
    regr: 0.01  # Regularization factor in Bayesian loss. float
    prior_p: 0.01 
    # Training parameters
    max_epochs: 200  # Maximum number of epochs for training
    patience: 10  # Patience for early stopping. int
    frequency: 2  # Frequency for early stopping test. int

  GraNDAG: 
    run: false
    device_type: gpu
    hidden_num: 0

  MCSL:
    run: false
    device_type: gpu
    num_hidden_layers: 0

  DiBS: 
    run: false
    steps: 3000
    n_posterior_samples: 100